version: '3'

services:
  zookeeper:
    image: zookeeper:latest
    restart: always
    hostname: zookeeper
    ports:
      - "2181:2181"
      - "8080:8080"
      - "2888:2888"
      - "3888:3888"
    networks:
      - kafkazoonetwork
    volumes:
      - ./zoo/zoo.cfg:/conf/zoo.cfg
      - ./zoo/myid:/data/myid
      - ./zoo/logs:/logs/
      - ./zoo/conf:/conf/


  kafka-broker:
    image: bitnami/kafka:latest
    hostname: kafka
    restart: always
    ports:
      - "9092:9092"
      - "9093:9093"
    env_file:
      - kafka/kafka.env
    volumes:
      - './private/server.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro'
      - './private/client.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro'
    depends_on:
      - zookeeper
    networks:
      - kafkazoonetwork
  

networks:
  kafkazoonetwork:
 
      
    
